version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data